// SPDX-License-Identifier: MIT
//
// The window.
//
// The platform's own webview -- WebView2, WKWebView, WebKitGTK -- on a page
// compiled into the binary. It lives on App rather than beside it because it
// draws App's session rather than owning one: there was an ImGui loop here
// doing the same job, and replacing it changed nothing below this file.
//
// Everything it is allowed to ask for goes through api::Surface, exactly as
// Python will. That is the point of
// building it this way: the interface gets no privileged access to the engine
// that another interface would not have, so nothing can quietly come to
// depend on being in-process.
#include "app.hpp"

#include <atomic>
#include <cstdio>
#include <cstring>
#include <string>

#if defined(CRUCIBLE_HAS_EMBEDDED_MARK)
namespace crucible::gui::art {
// Generated by cmake/EmbedBinary.cmake from packaging/icons/crucible.svg.
extern const unsigned char kMarkSvg[];
extern const unsigned int  kMarkSvg_size;
}  // namespace crucible::gui::art
#endif

#if defined(CRUCIBLE_HAS_EMBEDDED_FONT)
#include "fonts.hpp"
#endif

#if defined(CRUCIBLE_HAS_WEBVIEW)
#include <nlohmann/json.hpp>
#include <webview/webview.h>

#include "crucible/api/surface.hpp"
#endif

#if defined(CRUCIBLE_HAS_WEB_INDEX)
namespace crucible::gui::web {
// Generated by cmake/EmbedBinary.cmake from ui/index.html.
extern const unsigned char kIndexHtml[];
extern const unsigned int  kIndexHtml_size;
extern const unsigned char kRenderJs[];
extern const unsigned int  kRenderJs_size;
}  // namespace crucible::gui::web
#endif

namespace crucible::gui {
namespace {

/// base64, because a data: URI is the only way to hand a webview a font that
/// is not on disk anywhere.
std::string base64(const unsigned char* data, std::size_t size) {
    static constexpr char kAlphabet[] =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::string out;
    out.reserve((size + 2) / 3 * 4);
    for (std::size_t i = 0; i < size; i += 3) {
        const unsigned int a = data[i];
        const unsigned int b = i + 1 < size ? data[i + 1] : 0;
        const unsigned int c = i + 2 < size ? data[i + 2] : 0;
        const unsigned int triple = (a << 16) | (b << 8) | c;
        out += kAlphabet[(triple >> 18) & 0x3F];
        out += kAlphabet[(triple >> 12) & 0x3F];
        out += i + 1 < size ? kAlphabet[(triple >> 6) & 0x3F] : '=';
        out += i + 2 < size ? kAlphabet[triple & 0x3F] : '=';
    }
    return out;
}

/// The flame, as a data URI the page can put in an <img>. Empty when this
/// build has no artwork compiled in, and the page then shows the wordmark on
/// its own, which is what it falls back to.
std::string mark_data_uri() {
#if defined(CRUCIBLE_HAS_EMBEDDED_MARK)
    return "data:image/svg+xml;base64,"
         + base64(art::kMarkSvg, art::kMarkSvg_size);
#else
    return {};
#endif
}

/// The @font-face rules, or nothing when this build has no font compiled in --
/// in which case the page falls back to whatever monospace the machine has,
/// which is what its font stack says anyway.
std::string font_faces() {
#if defined(CRUCIBLE_HAS_EMBEDDED_FONT)
    const auto face = [](const char* weight, const unsigned char* data, unsigned int size) {
        return std::string("@font-face{font-family:'JetBrains Mono';font-weight:")
             + weight + ";font-display:block;src:url(data:font/ttf;base64,"
             + base64(data, size) + ") format('truetype')}";
    };
    return "<style>" + face("400", fonts::kRegular, fonts::kRegular_size)
                     + face("700", fonts::kBold,    fonts::kBold_size) + "</style>";
#else
    return {};
#endif
}

}  // namespace

int App::run_web() {
#if !defined(CRUCIBLE_HAS_WEBVIEW) || !defined(CRUCIBLE_HAS_WEB_INDEX)
    // Unreachable through CMake, which stops at configure time when there is
    // no webview to link. Kept because the guard is what makes that a
    // sentence rather than a link error: this function is declared
    // unconditionally, and compiling the file only when the webview is
    // present breaks the build the moment anything calls it -- which is
    // exactly how this was found.
    std::fprintf(stderr,
                 "crucible: this build has no window compiled into it.\n"
                 "          Reconfigure against WebKitGTK, WebView2 or WKWebView.\n");
    return 1;
#else
    engine_->start();

    // From the cache first, which costs a file read, and then on a thread if
    // it is time to ask again. The answer arrives as a notice, through the
    // same wake everything else uses.
    begin_update_check();

    webview::webview view(/*debug=*/false, nullptr);
    view.set_title("Crucible");
    view.set_size(1180, 760, WEBVIEW_HINT_NONE);

    api::Surface surface(api::Deps{
        engine_.get(), &state_,
        [this] { return project_root(); },
        [this] { return config_; },
        [this](Config edited) -> std::string {
            // The same path the window's settings screen takes, so the two
            // cannot apply a change differently.
            update_config([&edited](Config& live) { live = std::move(edited); });
            return {};
        },
        [this](std::filesystem::path root) -> std::string {
            open_project(root);
            return project_error_;
        },
        [this] {
            return pending_trust_ ? *pending_trust_ : std::filesystem::path{};
        },
        [this](bool trusted) {
            if (!pending_trust_) {
                return;
            }
            const std::filesystem::path root = *pending_trust_;
            pending_trust_.reset();
            if (trusted) {
                trust_.trust(root);
                open_project(root);
            }
        },
        [this](std::string session) -> std::string { return resume_session(session); },
        [this](std::string recipe) -> std::string { return begin_test(recipe); },
        [this] { end_test(); },
        [this](std::string recipe) -> std::string { return keep_tested(recipe); },
        // Read at call time, not captured: wake_ is set further down, once
        // the webview this pokes exists.
        [this] { if (wake_) { wake_(); } },
        &trainer_,
        &runtime_builder_,
        &pyenv_installer_,
    });

    // The one binding. Not one per operation: a method per engine call would
    // put the surface's vocabulary in two places and let them drift, and this
    // way adding a method to the API adds it to every interface at once.
    view.bind("rpc", [&surface](const std::string& args) -> std::string {
        // webview hands arguments as a JSON array, so the request is the
        // first element -- a string containing JSON rather than JSON itself,
        // which keeps the page's side symmetrical with Python's.
        const auto parsed = nlohmann::json::parse(args, nullptr, false);
        const std::string request =
            parsed.is_array() && !parsed.empty() && parsed[0].is_string()
                ? parsed[0].get<std::string>()
                : std::string{};
        // A JSON string, because that is what bind must return: the page
        // parses it once more, which is cheap and keeps one encoder.
        return nlohmann::json(surface.handle(request)).dump();
    });

    // How the engine reaches the screen. dispatch() is the only thread-safe
    // entry point a webview has, and the engine calls this from its own
    // thread.
    //
    // A flag rather than a queue of snapshots: several wakes between two
    // frames should produce one redraw of the current state, not a backlog of
    // stale ones.
    std::atomic<bool> dirty{false};
    wake_ = [this, &view, &dirty] {
        if (dirty.exchange(true)) {
            return;   // a redraw is already on its way
        }
        view.dispatch([this, &view, &dirty] {
            dirty.store(false);
            // The housekeeping the window's frame loop used to do.
            //
            // None of it belongs to drawing, but all of it has to happen on
            // this thread and this is the only thing that runs on it. Each
            // one checks first and does nothing almost every time: a wake
            // arrives per token, and writing the session file that often
            // would be the most expensive thing in the program.
            persist_session();
            absorb_written_examples();
            collect_update_check();

            // Read on the dispatch thread rather than on the engine's, so the
            // page is given the state as it is when it is drawn rather than
            // as it was when the wake was queued.
            view.eval("window.crucibleSnapshot && window.crucibleSnapshot("
                      + api::snapshot_json(state_.snapshot()) + ")");
        });
    };

    // JetBrains Mono, handed to the page as a data URI built from the same
    // bytes the window used. The alternative is asking the machine for a
    // monospace font and taking whatever it has, which on three platforms is
    // three different faces and none of them this one.
    std::string page(reinterpret_cast<const char*>(web::kIndexHtml), web::kIndexHtml_size);
    const std::string faces = font_faces();
    if (const std::size_t at = page.find("</head>"); at != std::string::npos && !faces.empty()) {
        page.insert(at, faces);
    }
    // The page asks for the mark by name and this is where the name is
    // answered; a build without artwork leaves the placeholder empty and the
    // img collapses to nothing.
    // The text-to-markup functions, ahead of the page's own script so they are
    // defined when it runs. They are a separate file because they are the part
    // worth testing, and tests/test_ui_js.cpp runs exactly these bytes.
    if (const std::size_t at = page.find("<script>"); at != std::string::npos) {
        const std::string render =
            "<script>\n"
            + std::string(reinterpret_cast<const char*>(web::kRenderJs), web::kRenderJs_size)
            + "\n</script>\n";
        page.insert(at, render);
    }

    if (const std::size_t at = page.find("CRUCIBLE_MARK_SRC"); at != std::string::npos) {
        page.replace(at, std::strlen("CRUCIBLE_MARK_SRC"), mark_data_uri());
    }
    view.set_html(page);
    view.run();

    // The engine outlives the window otherwise, and its worker calls back into
    // objects that are about to go out of scope.
    wake_ = nullptr;
    engine_->stop();
    return 0;
#endif
}

}  // namespace crucible::gui
