// SPDX-License-Identifier: MIT
//
// The web interface's window.
//
// Same program, same engine, same configuration -- a different thing drawing
// it. App owns the session either way; this is an alternative to the ImGui
// loop in app.cpp rather than a second application, which is why it lives on
// App rather than beside it.
//
// Everything it is allowed to ask for goes through api::Surface, exactly as
// the TypeScript will and exactly as Python will. That is the point of
// building it this way: the interface gets no privileged access to the engine
// that another interface would not have, so nothing can quietly come to
// depend on being in-process.
#include "app.hpp"

#include <atomic>
#include <cstdio>
#include <string>

#if defined(CRUCIBLE_HAS_WEBVIEW)
#include <nlohmann/json.hpp>
#include <webview/webview.h>

#include "crucible/api/surface.hpp"
#endif

#if defined(CRUCIBLE_HAS_WEB_INDEX)
namespace crucible::gui::web {
// Generated by cmake/EmbedBinary.cmake from ui/index.html.
extern const unsigned char kIndexHtml[];
extern const unsigned int  kIndexHtml_size;
}  // namespace crucible::gui::web
#endif

namespace crucible::gui {

int App::run_web() {
#if !defined(CRUCIBLE_HAS_WEBVIEW) || !defined(CRUCIBLE_HAS_WEB_INDEX)
    // Always defined, so that whether the option was on is a runtime message
    // rather than a link error. The alternative -- compiling this file only
    // when the webview is available -- breaks the default build the moment
    // anything calls it, which is exactly how this was found.
    std::fprintf(stderr,
                 "crucible: this build has no web interface. Configure with\n"
                 "          -DCRUCIBLE_BUILD_WEBUI=ON to compile one in.\n");
    return 1;
#else
    engine_->start();

    webview::webview view(/*debug=*/false, nullptr);
    view.set_title("Crucible");
    view.set_size(1180, 760, WEBVIEW_HINT_NONE);

    api::Surface surface(api::Deps{
        engine_.get(), &state_,
        [this] { return project_root(); },
        [this] { return config_; },
        [this](Config edited) -> std::string {
            // The same path the window's settings screen takes, so the two
            // cannot apply a change differently.
            update_config([&edited](Config& live) { live = std::move(edited); });
            return {};
        },
        [this](std::filesystem::path root) -> std::string {
            open_project(root);
            return project_error_;
        },
        [this] {
            return pending_trust_ ? *pending_trust_ : std::filesystem::path{};
        },
        [this](bool trusted) {
            if (!pending_trust_) {
                return;
            }
            const std::filesystem::path root = *pending_trust_;
            pending_trust_.reset();
            if (trusted) {
                trust_.trust(root);
                open_project(root);
            }
        },
    });

    // The one binding. Not one per operation: a method per engine call would
    // put the surface's vocabulary in two places and let them drift, and this
    // way adding a method to the API adds it to every interface at once.
    view.bind("rpc", [&surface](const std::string& args) -> std::string {
        // webview hands arguments as a JSON array, so the request is the
        // first element -- a string containing JSON rather than JSON itself,
        // which keeps the page's side symmetrical with Python's.
        const auto parsed = nlohmann::json::parse(args, nullptr, false);
        const std::string request =
            parsed.is_array() && !parsed.empty() && parsed[0].is_string()
                ? parsed[0].get<std::string>()
                : std::string{};
        // A JSON string, because that is what bind must return: the page
        // parses it once more, which is cheap and keeps one encoder.
        return nlohmann::json(surface.handle(request)).dump();
    });

    // The engine wakes this instead of GLFW while the web interface is the one
    // running. dispatch() is the only thread-safe entry point a webview has,
    // and the engine calls this from its own thread.
    //
    // A flag rather than a queue of snapshots: several wakes between two
    // frames should produce one redraw of the current state, not a backlog of
    // stale ones.
    std::atomic<bool> dirty{false};
    wake_ = [this, &view, &dirty] {
        if (dirty.exchange(true)) {
            return;   // a redraw is already on its way
        }
        view.dispatch([this, &view, &dirty] {
            dirty.store(false);
            // Read on the dispatch thread rather than on the engine's, so the
            // page is given the state as it is when it is drawn rather than
            // as it was when the wake was queued.
            view.eval("window.crucibleSnapshot && window.crucibleSnapshot("
                      + api::snapshot_json(state_.snapshot()) + ")");
        });
    };

    view.set_html(std::string(reinterpret_cast<const char*>(web::kIndexHtml),
                              web::kIndexHtml_size));
    view.run();

    // The engine outlives the window otherwise, and its worker calls back into
    // objects that are about to go out of scope.
    wake_ = nullptr;
    engine_->stop();
    return 0;
#endif
}

}  // namespace crucible::gui
