// SPDX-License-Identifier: MIT
//
// The window.
//
// The platform's own webview -- WebView2, WKWebView, WebKitGTK -- on a page
// compiled into the binary. It lives on App rather than beside it because it
// draws App's session rather than owning one.
//
// Everything the page is allowed to ask for goes through api::Surface, exactly
// as Python will. That is the point of building it this way: the interface
// gets no privileged access to the engine that another interface would not
// have, so nothing can quietly come to depend on being in-process.
//
// Three things here are about one fact, which is that a window has a single
// thread that draws and anything slow on it is a frozen window:
//
//   - a request the surface says is only a lookup is answered on a worker
//     thread, and the page's promise is resolved when it comes back;
//   - the state is pushed to the page at most a few dozen times a second,
//     however fast the tokens arrive;
//   - the file dialog is the platform's own, shown without blocking.
#include "app.hpp"

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstdio>
#include <cstring>
#include <memory>
#include <mutex>
#include <string>
#include <thread>

#if defined(CRUCIBLE_HAS_EMBEDDED_MARK)
namespace crucible::gui::art {
// Generated by cmake/EmbedBinary.cmake from packaging/icons/crucible.svg.
extern const unsigned char kMarkSvg[];
extern const unsigned int  kMarkSvg_size;
}  // namespace crucible::gui::art
#endif

#if defined(CRUCIBLE_HAS_EMBEDDED_FONT)
#include "fonts.hpp"
#endif

#if defined(CRUCIBLE_HAS_WEBVIEW)
#include <nlohmann/json.hpp>
#include <webview/webview.h>

#include "crucible/api/surface.hpp"
#include "dialogs.hpp"
#endif

#if defined(CRUCIBLE_HAS_WEB_INDEX)
namespace crucible::gui::web {
// Generated by cmake/BundlePage.cmake from everything under ui/, and then by
// cmake/EmbedBinary.cmake from that.
extern const unsigned char kPageHtml[];
extern const unsigned int  kPageHtml_size;
}  // namespace crucible::gui::web
#endif

namespace crucible::gui {
namespace {

/// base64, because a data: URI is the only way to hand a webview a font that
/// is not on disk anywhere.
std::string base64(const unsigned char* data, std::size_t size) {
    static constexpr char kAlphabet[] =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::string out;
    out.reserve((size + 2) / 3 * 4);
    for (std::size_t i = 0; i < size; i += 3) {
        const unsigned int a = data[i];
        const unsigned int b = i + 1 < size ? data[i + 1] : 0;
        const unsigned int c = i + 2 < size ? data[i + 2] : 0;
        const unsigned int triple = (a << 16) | (b << 8) | c;
        out += kAlphabet[(triple >> 18) & 0x3F];
        out += kAlphabet[(triple >> 12) & 0x3F];
        out += i + 1 < size ? kAlphabet[(triple >> 6) & 0x3F] : '=';
        out += i + 2 < size ? kAlphabet[triple & 0x3F] : '=';
    }
    return out;
}

/// The flame, as a data URI the page can put in an <img>. Empty when this
/// build has no artwork compiled in, and the page then shows the wordmark on
/// its own, which is what it falls back to.
std::string mark_data_uri() {
#if defined(CRUCIBLE_HAS_EMBEDDED_MARK)
    return "data:image/svg+xml;base64,"
         + base64(art::kMarkSvg, art::kMarkSvg_size);
#else
    return {};
#endif
}

/// The @font-face rules, or nothing when this build has no font compiled in --
/// in which case the page falls back to whatever monospace the machine has,
/// which is what its font stack says anyway.
std::string font_faces() {
#if defined(CRUCIBLE_HAS_EMBEDDED_FONT)
    const auto face = [](const char* weight, const unsigned char* data, unsigned int size) {
        return std::string("@font-face{font-family:'JetBrains Mono';font-weight:")
             + weight + ";font-display:block;src:url(data:font/ttf;base64,"
             + base64(data, size) + ") format('truetype')}";
    };
    return "<style>" + face("400", fonts::kRegular, fonts::kRegular_size)
                     + face("700", fonts::kBold,    fonts::kBold_size) + "</style>";
#else
    return {};
#endif
}

#if defined(CRUCIBLE_HAS_WEBVIEW) && defined(CRUCIBLE_HAS_WEB_INDEX)

using json = nlohmann::json;

/// The first argument of a call from the page.
///
/// webview hands a binding its arguments as the text of a JSON array, so what
/// the page passed is element zero.
json first_argument(const std::string& arguments) {
    const json parsed = json::parse(arguments, nullptr, false);
    return parsed.is_array() && !parsed.empty() ? parsed[0] : json(nullptr);
}

/// Whether the window is still there to be spoken to.
///
/// A worker can finish its errand after the window has closed. It asks here
/// before it touches the webview, and closing waits here for any that are in
/// the middle of doing so.
struct Gate {
    std::mutex mutex;
    bool       open = true;
};

/// Decides when the page is next told how things stand.
///
/// The engine wakes the window once per token, and a snapshot is the whole
/// transcript. Pushing one per token makes the cost of a reply grow with the
/// square of its length and buys nothing: a screen shows sixty frames a
/// second and a person reads rather fewer. So a wake only raises a flag, and
/// a thread of its own turns the flag into at most one push per interval.
class Pusher {
public:
    explicit Pusher(std::function<void()> push) : push_(std::move(push)) {
        thread_ = std::thread([this] { run(); });
    }

    ~Pusher() {
        {
            const std::lock_guard<std::mutex> lock(mutex_);
            closing_ = true;
        }
        changed_.notify_all();
        if (thread_.joinable()) {
            thread_.join();
        }
    }

    Pusher(const Pusher&)            = delete;
    Pusher& operator=(const Pusher&) = delete;

    /// Something changed. Safe from any thread, and cheap: the engine calls
    /// it from the loop that generates tokens.
    void wake() {
        {
            const std::lock_guard<std::mutex> lock(mutex_);
            dirty_ = true;
        }
        changed_.notify_one();
    }

    /// The push that was asked for has been drawn, so another may be sent.
    /// Called on the window's thread, from inside the push itself.
    void landed() {
        {
            const std::lock_guard<std::mutex> lock(mutex_);
            in_flight_ = false;
        }
        changed_.notify_one();
    }

private:
    /// About thirty a second: faster than text can be read as it streams, and
    /// slow enough that a long transcript is not being re-sent for nothing.
    static constexpr std::chrono::milliseconds kInterval{33};

    void run() {
        std::unique_lock<std::mutex> lock(mutex_);
        for (;;) {
            // Not while one is still on its way. If the window's thread is
            // busy, queueing a second snapshot behind the first only makes it
            // busier; the flag stays up and the next push carries both.
            changed_.wait(lock, [this] { return closing_ || (dirty_ && !in_flight_); });
            if (closing_) {
                return;
            }
            dirty_     = false;
            in_flight_ = true;
            lock.unlock();
            push_();
            lock.lock();
            changed_.wait_for(lock, kInterval, [this] { return closing_; });
        }
    }

    std::function<void()>   push_;
    std::mutex              mutex_;
    std::condition_variable changed_;
    bool                    dirty_     = false;
    bool                    in_flight_ = false;
    bool                    closing_   = false;
    std::thread             thread_;
};

#endif

}  // namespace

int App::run() {
#if !defined(CRUCIBLE_HAS_WEBVIEW) || !defined(CRUCIBLE_HAS_WEB_INDEX)
    // Unreachable through CMake, which stops at configure time when there is
    // no webview to link. Kept because the guard is what makes that a
    // sentence rather than a link error: this function is declared
    // unconditionally, and compiling the file only when the webview is
    // present breaks the build the moment anything calls it -- which is
    // exactly how this was found.
    std::fprintf(stderr,
                 "crucible: this build has no window compiled into it.\n"
                 "          Reconfigure against WebKitGTK, WebView2 or WKWebView.\n");
    return 1;
#else
    webview::webview view(/*debug=*/false, nullptr);
    view.set_title("Crucible");
    view.set_size(1180, 760, WEBVIEW_HINT_NONE);

    // Shared with the workers, so an errand that outlives this function is
    // not left holding a reference into its stack.
    //
    // The cast is because App is a Host privately: nothing outside this class
    // can treat a session as one, and std::make_shared is outside it.
    const auto surface = std::make_shared<api::Surface>(static_cast<api::Host&>(*this));
    const auto gate    = std::make_shared<Gate>();

    // --- the state, pushed --------------------------------------------------
    //
    // dispatch() is the only thread-safe way into a webview, and it is how
    // everything that is not the window's own thread reaches the screen.
    std::string title = "Crucible";
    Pusher*     pushing = nullptr;
    Pusher      pusher([this, &view, &surface, &title, &pushing, gate] {
        view.dispatch([this, &view, &surface, &title, &pushing, gate] {
            // The window may have closed since this was queued. A webview
            // drains its queue on the way out, so this can run after the
            // window it would draw into is gone -- and after the pusher that
            // queued it is, too. Closing the window while a model was still
            // loading did exactly that, and took the process down with it.
            // The gate is closed the moment the window is, on this thread,
            // so reading it here needs no lock.
            if (!gate->open) {
                return;
            }

            // On the window's thread, which is the session's thread: the one
            // place the jobs a frame loop used to do can still be done.
            housekeeping();

            // The title follows the project, as the old window's did. Set
            // only when it changes; some window managers repaint the whole
            // frame on every call.
            const std::filesystem::path root = project_root();
            const std::string wanted =
                root.empty() ? std::string("Crucible")
                             : (root.filename().empty() ? root.string()
                                                        : root.filename().string())
                                   + " \xE2\x80\x94 Crucible";
            if (wanted != title) {
                title = wanted;
                view.set_title(title);
            }

            // Read here rather than where the wake was raised, so the page
            // is given the state as it is when it is drawn rather than as it
            // was when something changed.
            view.eval("window.crucibleSnapshot && window.crucibleSnapshot("
                      + surface->snapshot() + ")");
            if (pushing != nullptr) {
                pushing->landed();
            }
        });
    });
    pushing = &pusher;
    set_wake([&pusher] { pusher.wake(); });

    // --- the one door -------------------------------------------------------
    //
    // One binding, not one per operation: a method per engine call would put
    // the surface's vocabulary in two places and let them drift, and this way
    // adding a method to the API adds it to every interface at once.
    //
    // The request is a string of JSON and so is the reply, which keeps the
    // page's side symmetrical with Python's. The page parses it once more;
    // that is cheap and it keeps one encoder.
    view.bind("rpc",
              [this, &view, &pusher, surface, gate](const std::string& id,
                                                    const std::string& arguments, void*) {
                  const json request = first_argument(arguments);
                  api::Prepared call =
                      surface->prepare(request.is_string() ? request.get<std::string>()
                                                           : std::string());
                  if (!call.background) {
                      view.resolve(id, 0, json(surface->run(call)).dump());
                      // An action may have changed something only the
                      // session knows -- a folder now waiting to be trusted,
                      // a seat taken away -- and nothing else would say so.
                      // The engine wakes the page when *it* changes; this is
                      // the same courtesy for everything that is not the
                      // engine. Several in a row still make one redraw.
                      pusher.wake();
                      return;
                  }
                  // A lookup: slow, and touching nothing of the session's.
                  // The page awaits it like any other call and the window
                  // goes on drawing in the meantime.
                  workers_.post([&view, surface, gate, id, call = std::move(call)] {
                      const std::string reply = json(surface->run(call)).dump();
                      const std::lock_guard<std::mutex> lock(gate->mutex);
                      if (gate->open) {
                          view.resolve(id, 0, reply);
                      }
                  });
              },
              nullptr);

    // --- the platform's file dialog -----------------------------------------
    //
    // Not part of the surface, deliberately. It is a thing a window can do,
    // and the Python orchestrator on the other end of a pipe has no window to
    // do it over. The page falls back to a picker of its own when the answer
    // comes back unsupported.
    view.bind("nativeDialog",
              [&view, gate](const std::string& id, const std::string& arguments, void*) {
                  const json wanted = first_argument(arguments);
                  dialogs::Request request;
                  if (wanted.is_object()) {
                      request.folder      = wanted.value("folder", false);
                      request.title       = wanted.value("title", std::string{});
                      request.start       = wanted.value("start", std::string{});
                      request.filter_name = wanted.value("filter", std::string{});
                      if (wanted.contains("extensions") && wanted["extensions"].is_array()) {
                          for (const json& one : wanted["extensions"]) {
                              if (one.is_string()) {
                                  request.extensions.push_back(one.get<std::string>());
                              }
                          }
                      }
                  }
                  const auto handle = view.window();
                  dialogs::pick(handle.ok() ? handle.value() : nullptr, request,
                                [&view, gate, id](dialogs::Answer answer) {
                                    const std::lock_guard<std::mutex> lock(gate->mutex);
                                    if (!gate->open) {
                                        return;
                                    }
                                    view.resolve(id, 0,
                                                 json{{"supported", answer.supported},
                                                      {"path", answer.path}}.dump());
                                });
              },
              nullptr);

    engine_->start();

    // From the cache first, which costs a file read, and then on a worker if
    // it is time to ask again. The answer arrives as a notice, through the
    // same wake everything else uses.
    begin_update_check();

    // --- the page -------------------------------------------------------------
    //
    // One document, assembled at build time from the files under ui/. Two
    // things are still filled in here because they are not text anybody
    // edits: the typeface and the mark, both handed over as data URIs built
    // from the bytes compiled into this binary. The alternative for the font
    // is asking the machine for a monospace and taking whatever it has, which
    // on three platforms is three different faces and none of them this one.
    std::string page(reinterpret_cast<const char*>(web::kPageHtml), web::kPageHtml_size);
    const std::string faces = font_faces();
    if (const std::size_t at = page.find("</head>"); at != std::string::npos && !faces.empty()) {
        page.insert(at, faces);
    }
    // A build without artwork leaves the placeholder empty and the page shows
    // the wordmark on its own.
    constexpr const char* kMarkPlaceholder = "CRUCIBLE_MARK_SRC";
    for (std::size_t at = page.find(kMarkPlaceholder); at != std::string::npos;
         at = page.find(kMarkPlaceholder)) {
        page.replace(at, std::strlen(kMarkPlaceholder), mark_data_uri());
    }
    view.set_html(page);
    view.run();

    // --- closing --------------------------------------------------------------
    //
    // In this order. The gate first, so nothing speaks to the webview from
    // here on -- not a worker with an answer, and not a redraw still sitting
    // in the webview's own queue; then the engine, whose thread calls the
    // wake; and only then is the wake taken away. The pusher and the webview
    // go as this function returns, pusher first, which is the order they were
    // declared in reversed.
    {
        const std::lock_guard<std::mutex> lock(gate->mutex);
        gate->open = false;
    }
    engine_->stop();
    set_wake(nullptr);
    return 0;
#endif
}

}  // namespace crucible::gui
