// SPDX-License-Identifier: MIT
#include "crucible/app/cli.hpp"

#include <iostream>

#include "crucible/app/update.hpp"
#include "crucible/config/paths.hpp"

#if defined(CRUCIBLE_HAS_NOTICES)
namespace crucible::app::embedded {
// Generated by cmake/EmbedBinary.cmake from packaging/licenses/NOTICES.txt.
extern const unsigned char kNotices[];
extern const unsigned int  kNotices_size;
}  // namespace crucible::app::embedded
#endif

namespace crucible::app {
namespace {

// Crucible's mark, in braille, from packaging/flame.txt -- the one copy the
// two installers, the README and this are all pasted from. The terminal
// sprite draws the same flame in plain ASCII instead, because it has to
// animate and it has a no-Unicode fallback; this is a still, and can afford
// the resolution braille gives it.
//
// Printed as UTF-8. main() puts the console into UTF-8 first, which on
// Windows is the difference between this and twelve rows of question marks.
constexpr const char* kBanner = R"(
      ⠀⠀⠀⠀⠀⠀⢱⣆⠀⠀⠀⠀⠀⠀
      ⠀⠀⠀⠀⠀⠀⠈⣿⣷⡀⠀⠀⠀⠀
      ⠀⠀⠀⠀⠀⠀⢸⣿⣿⣷⣧⠀⠀⠀
      ⠀⠀⠀⠀⡀⢠⣿⡟⣿⣿⣿⡇⠀⠀
      ⠀⠀⠀⠀⣳⣼⣿⡏⢸⣿⣿⣿⢀⠀   Crucible )" CRUCIBLE_VERSION R"(
      ⠀⠀⠀⣰⣿⣿⡿⠁⢸⣿⣿⡟⣼⡆   a local LLM engine that delegates.
      ⢰⢀⣾⣿⣿⠟⠀⠀⣾⢿⣿⣿⣿⣿
      ⢸⣿⣿⣿⡏⠀⠀⠀⠃⠸⣿⣿⣿⡿
      ⢳⣿⣿⣿⠀⠀⠀⠀⠀⠀⢹⣿⡿⡁
      ⠀⠹⣿⣿⡄⠀⠀⠀⠀⠀⢠⣿⡞⠁
      ⠀⠀⠈⠛⢿⣄⠀⠀⠀⣠⠞⠋⠀⠀
      ⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⠀
)";

void print_usage() {
    std::cout << kBanner << R"(
usage: crucible [options]

  -h, --help       show this and exit
  -v, --version    print the version and exit
      --config     print the config file path and exit
      --licenses   print the third-party notices and exit
      --uninstall  remove Crucible, its config, and its data
      --no-trust   skip the folder trust prompt for this run
  -y, --yes        with --uninstall, answer yes to everything

      --ui window|web     which interface to open (default: window)

      --install-runtimes  install the compute backends this machine can use
      --runtime-status    say which backends are installed and active, and exit
      --install-trainer   install the Python environment fine-tuning needs
      --trainer-status    say whether that environment is usable, and exit
      --trainer-flavor F  cuda, cpu or mlx (default: what the hardware says)
      --force             with --install-trainer, rebuild one that is already there
      --quiet             less output, for a script

Crucible reads its configuration from:
)" << "  " << paths::config_file().string() << "\n\n";
}

}  // namespace

const char* banner() {
    return kBanner;
}

Options parse_arguments(int argc, char** argv) {
    Options options;

    for (int i = 1; i < argc; ++i) {
        const std::string argument = argv[i];

        if (argument == "-h" || argument == "--help") {
            print_usage();
            options.should_exit = true;
            return options;
        }
        if (argument == "-v" || argument == "--version") {
            std::cout << "crucible " CRUCIBLE_VERSION "\n";
            // Whatever the last check found, read from the cache. No network:
            // `--version` is what a script and a bug report run, and neither
            // should wait on GitHub to hear what this binary already knows.
            update::State state;
            if (update::read_cache(state) && update::newer_than_this(state)) {
                std::cout << "  " << state.latest << " is available -- update with:\n"
                          << "  " << update::update_command() << "\n";
            }
            options.should_exit = true;
            return options;
        }
        if (argument == "--licenses") {
            // Printed by the binary rather than shipped beside it: an
            // AppImage and a .app bundle are each one file as far as a user
            // is concerned, and a notice in a folder next to the program is
            // a notice that gets separated from it.
#if defined(CRUCIBLE_HAS_NOTICES)
            std::cout.write(reinterpret_cast<const char*>(embedded::kNotices),
                            static_cast<std::streamsize>(embedded::kNotices_size));
#else
            std::cout << "this build has no notices compiled in\n";
#endif
            options.should_exit = true;
            return options;
        }
        if (argument == "--config") {
            std::cout << paths::config_file().string() << "\n";
            options.should_exit = true;
            return options;
        }
        if (argument == "--ui") {
            const std::string which = i + 1 < argc ? argv[++i] : "";
            if (which != "window" && which != "web") {
                std::cerr << "crucible: --ui takes 'window' or 'web'\n";
                options.should_exit = true;
                options.exit_code   = 2;
                return options;
            }
            options.web_ui = which == "web";
            continue;
        }
        if (argument == "--install-runtimes") { options.install_runtimes = true; continue; }
        if (argument == "--runtime-status")   { options.runtime_status   = true; continue; }
        if (argument == "--install-trainer") { options.install_trainer = true; continue; }
        if (argument == "--trainer-status")  { options.trainer_status  = true; continue; }
        if (argument == "--force")           { options.force           = true; continue; }
        if (argument == "--quiet")           { options.quiet           = true; continue; }
        if (argument == "--trainer-flavor") {
            if (i + 1 >= argc) {
                std::cerr << "crucible: --trainer-flavor needs cuda, cpu or mlx\n";
                options.should_exit = true;
                options.exit_code   = 2;
                return options;
            }
            options.trainer_flavor = argv[++i];
            continue;
        }
        if (argument == "--no-trust") { options.skip_trust = true;  continue; }
        if (argument == "--uninstall") { options.uninstall = true;  continue; }
        if (argument == "-y" || argument == "--yes") { options.assume_yes = true; continue; }

        std::cerr << "crucible: unknown option '" << argument << "' (try --help)\n";
        options.should_exit = true;
        options.exit_code   = 2;
        return options;
    }

    return options;
}

}  // namespace crucible::app
