// SPDX-License-Identifier: MIT
#include "crucible/lab/pyenv.hpp"

#include <algorithm>
#include <chrono>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <sstream>
#include <system_error>

#include <nlohmann/json.hpp>

#include "crucible/config/paths.hpp"
#include "crucible/runtime/devices.hpp"
#include "crucible/util/platform.hpp"

#if defined(CRUCIBLE_HAS_TRAINER_SCRIPT)
namespace crucible::lab::embedded {
// Generated by cmake/EmbedBinary.cmake from scripts/trainer/finetune.py.
extern const unsigned char kFinetunePy[];
extern const unsigned int  kFinetunePy_size;
}  // namespace crucible::lab::embedded
#endif

namespace crucible::lab::pyenv {
namespace {

using json = nlohmann::json;

constexpr std::uint64_t kMiB = 1024ULL * 1024;
constexpr std::uint64_t kGiB = 1024ULL * kMiB;

constexpr std::size_t kMaxLogLines = 4000;
constexpr std::size_t kTailLines   = 30;

/// The lowest Python the training stack still publishes wheels for. Below it
/// pip resolves happily and lands on versions from before any of this worked,
/// which fails much later and much less clearly.
constexpr int kMinMinor = 10;

/// Interpreters to try, newest first.
///
/// Named versions before the bare name: `python3` on a distribution that has
/// moved on can be 3.13 before torch has wheels for it, and the machine
/// usually also has the 3.12 that does.
const char* const kCandidates[] = {
    "python3.12", "python3.11", "python3.10", "python3.13", "python3", "python",
};

std::string trimmed(std::string text) {
    while (!text.empty() && (text.back() == '\n' || text.back() == '\r' || text.back() == ' ')) {
        text.pop_back();
    }
    return text;
}

/// Run `argv` and return everything it printed, or nothing if it would not
/// start. For the short questions -- what version are you, does this import.
std::string capture(const std::vector<std::string>& argv, int& status) {
    util::Subprocess child;
    std::string      error;
    status = -1;
    if (!child.start(argv, {}, {}, error)) {
        return {};
    }
    std::string all;
    std::string line;
    while (child.read_line(line)) {
        all += line;
        all += '\n';
    }
    status = child.wait();
    return all;
}

/// "3.12.4" -> 12. Returns -1 for anything that is not a version.
int minor_of(const std::string& version) {
    const std::size_t first = version.find('.');
    if (version.rfind("3.", 0) != 0 || first == std::string::npos) {
        return -1;
    }
    try {
        return std::stoi(version.substr(first + 1));
    } catch (const std::exception&) {
        return -1;
    }
}

/// A compute capability as CMake and nvidia-smi write it: "12.0" is 120.
int capability_from(const std::string& text) {
    int major = 0;
    int minor = 0;
    if (std::sscanf(text.c_str(), "%d.%d", &major, &minor) != 2) {
        return 0;
    }
    return major * 10 + minor;
}

/// The newest NVIDIA card in the machine, as a compute capability, or 0.
int newest_capability() {
    if (!util::on_path("nvidia-smi")) {
        return 0;
    }
    int status = -1;
    const std::string reply = capture(
        {"nvidia-smi", "--query-gpu=compute_cap", "--format=csv,noheader"}, status);
    if (status != 0) {
        return 0;
    }
    int         best = 0;
    std::string line;
    for (std::istringstream lines(reply); std::getline(lines, line);) {
        best = std::max(best, capability_from(line));
    }
    return best;
}

/// Which PyTorch build to take, by what the cards need.
///
/// This is not a detail. A torch wheel carries compiled kernels for a fixed
/// list of architectures, and a card newer than the list is not slow, it is
/// unusable -- `torch.cuda.is_available()` still says true, the import still
/// works, and the first kernel launch fails. Blackwell (sm_120) needs the
/// CUDA 12.8 build; everything up to Hopper is served by 12.4, which is the
/// older and better-tested one and so the default.
///
/// Measured here on an RTX 5060 Ti: the 12.4 wheel reports an arch list
/// ending at sm_90 and warns that the card is not compatible, then quietly
/// runs everything on the other two cards in the machine.
std::string cuda_index() {
    return newest_capability() >= 100 ? "https://download.pytorch.org/whl/cu128"
                                      : "https://download.pytorch.org/whl/cu124";
}

std::string now_stamp() {
    const auto      now   = std::chrono::system_clock::now();
    const std::time_t when = std::chrono::system_clock::to_time_t(now);
    const std::tm   parts = util::utc_time(when);
    char            buffer[32];
    if (std::strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M UTC", &parts) == 0) {
        return {};
    }
    return buffer;
}

std::uint64_t folder_bytes(const std::filesystem::path& dir) {
    std::error_code ec;
    std::uint64_t   total = 0;
    for (const std::filesystem::directory_entry& entry :
         std::filesystem::recursive_directory_iterator(
             dir, std::filesystem::directory_options::skip_permission_denied, ec)) {
        std::error_code each;
        if (entry.is_regular_file(each)) {
            total += entry.file_size(each);
        }
    }
    return total;
}

}  // namespace

// ---------------------------------------------------------------------------
// Flavors
// ---------------------------------------------------------------------------

std::string_view flavor_id(Flavor flavor) {
    switch (flavor) {
        case Flavor::Cuda: return "cuda";
        case Flavor::Mlx:  return "mlx";
        case Flavor::Cpu:  break;
    }
    return "cpu";
}

Flavor flavor_from_id(std::string_view id) {
    if (id == "cuda") { return Flavor::Cuda; }
    if (id == "mlx")  { return Flavor::Mlx; }
    return Flavor::Cpu;
}

/// What the hardware says it should be.
///
/// The device list is asked first because it is the truth -- it is what
/// llama.cpp actually found -- but it is empty until a GPU runtime has been
/// installed, and the training environment is put in place before any of that
/// has happened. So a driver query is the fallback: `nvidia-smi` exists if and
/// only if there is an NVIDIA driver, which is the thing a CUDA torch needs.
Flavor flavor_here() {
#if defined(__APPLE__) && defined(__aarch64__)
    return Flavor::Mlx;
#else
    for (const ComputeDevice& device : gpu_devices()) {
        if (device.backend == "CUDA") {
            return Flavor::Cuda;
        }
    }
    if (util::on_path("nvidia-smi")) {
        return Flavor::Cuda;
    }
    return Flavor::Cpu;
#endif
}

std::string_view flavor_note(Flavor flavor) {
    switch (flavor) {
        case Flavor::Cuda:
            return "QLoRA and LoRA on the card, which is the fast one";
        case Flavor::Mlx:
            return "LoRA on Apple Silicon through MLX";
        case Flavor::Cpu:
            break;
    }
    return "LoRA on the processor -- it works, and it is slow enough to plan around";
}

/// Measured from the wheels these resolve to, rounded to something honest.
/// The CUDA number is dominated by torch and the nvidia-* libraries it pulls
/// with it, which is why it is a different order of magnitude from the rest.
std::uint64_t download_bytes(Flavor flavor) {
    switch (flavor) {
        case Flavor::Cuda: return 3ULL * kGiB;
        case Flavor::Mlx:  return 350 * kMiB;
        case Flavor::Cpu:  break;
    }
    return 700 * kMiB;
}

std::uint64_t installed_bytes(Flavor flavor) {
    switch (flavor) {
        case Flavor::Cuda: return 7ULL * kGiB;
        case Flavor::Mlx:  return 900 * kMiB;
        case Flavor::Cpu:  break;
    }
    return 2ULL * kGiB;
}

/// Floors and ceilings rather than exact pins.
///
/// An exact pin on nine packages that are versioned against each other is a
/// resolve that fails the first time any one of them yanks a build, on a
/// machine that has no way to edit the list. A major-version ceiling stops
/// the breaking change; the resolved versions are recorded in the manifest
/// afterwards, which is the part worth being able to read back.
std::vector<Step> plan(Flavor flavor) {
    std::vector<Step> steps;

    if (flavor == Flavor::Mlx) {
        steps.push_back({"MLX", {"mlx>=0.18,<1", "mlx-lm>=0.19,<1"}, ""});
    } else {
        steps.push_back({flavor == Flavor::Cuda ? "PyTorch (CUDA)" : "PyTorch",
                         {"torch>=2.4,<3"},
                         flavor == Flavor::Cuda
                             ? cuda_index()
                             : "https://download.pytorch.org/whl/cpu"});
    }

    steps.push_back({"Transformers",
                     {"transformers>=4.44,<5", "accelerate>=0.33,<2",
                      "safetensors>=0.4,<1", "sentencepiece>=0.2,<1",
                      "protobuf>=4,<6"},
                     ""});
    steps.push_back({"Datasets", {"datasets>=2.20,<4"}, ""});

    if (flavor != Flavor::Mlx) {
        steps.push_back({"LoRA", {"peft>=0.12,<1"}, ""});
    }
    if (flavor == Flavor::Cuda) {
        // The four-bit quantizer QLoRA is. CUDA only: its processor path
        // exists and is slow enough that offering it would be a trap.
        steps.push_back({"QLoRA", {"bitsandbytes>=0.43,<1"}, ""});
    }

    // What turns the trained model into a file llama.cpp can load. Small, and
    // the last step for a reason -- everything above it is the fine-tune, and
    // this is the export.
    steps.push_back({"GGUF export", {"gguf>=0.10,<1", "numpy>=1.24,<3"}, ""});
    return steps;
}

std::vector<std::string> imports(Flavor flavor) {
    std::vector<std::string> names{"transformers", "datasets", "safetensors", "gguf"};
    if (flavor == Flavor::Mlx) {
        names.insert(names.begin(), {"mlx", "mlx_lm"});
        return names;
    }
    names.insert(names.begin(), {"torch", "peft"});
    if (flavor == Flavor::Cuda) {
        names.emplace_back("bitsandbytes");
    }
    return names;
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

std::filesystem::path root()          { return paths::data_dir() / "trainer"; }
std::filesystem::path venv_dir()      { return root() / "venv"; }
std::filesystem::path script()        { return root() / "finetune.py"; }
std::filesystem::path manifest_file() { return root() / "trainer.json"; }
std::filesystem::path log_file()      { return root() / "install.log"; }
std::filesystem::path runs_dir()      { return root() / "runs"; }

std::filesystem::path python() {
#if defined(_WIN32)
    return venv_dir() / "Scripts" / "python.exe";
#else
    return venv_dir() / "bin" / "python";
#endif
}

std::filesystem::path host_python(std::string& version) {
    version.clear();
    std::string best_seen;
    for (const char* name : kCandidates) {
        if (!util::on_path(name)) {
            continue;
        }
        int               status = -1;
        const std::string reported = trimmed(capture(
            {name, "-c", "import sys; print('%d.%d.%d' % sys.version_info[:3])"}, status));
        if (status != 0 || reported.empty()) {
            continue;
        }
        if (best_seen.empty()) {
            best_seen = reported;
        }
        if (minor_of(reported) >= kMinMinor) {
            // venv has to be there too. A Debian python3 without python3-venv
            // is the common case, and finding out at `python -m venv` is a
            // failure several steps after the one that could explain it.
            int venv_status = -1;
            capture({name, "-c", "import venv"}, venv_status);
            if (venv_status != 0) {
                best_seen = reported + " (no venv module)";
                continue;
            }
            version = reported;
            return std::filesystem::path(name);
        }
    }
    version = best_seen;
    return {};
}

std::string python_hint() {
    std::string version;
    if (!host_python(version).empty()) {
        return {};
    }
#if defined(_WIN32)
    return "install Python 3.12 from python.org, or: winget install Python.Python.3.12";
#elif defined(__APPLE__)
    return "install Python 3.12: brew install python@3.12";
#else
    if (util::on_path("apt-get")) {
        return "sudo apt-get install python3 python3-venv python3-pip";
    }
    if (util::on_path("dnf")) {
        return "sudo dnf install python3 python3-pip";
    }
    if (util::on_path("pacman")) {
        return "sudo pacman -S python python-pip";
    }
    if (util::on_path("zypper")) {
        return "sudo zypper install python3 python3-pip";
    }
    return "install Python 3.10 or newer, with its venv module";
#endif
}

// ---------------------------------------------------------------------------
// Status
// ---------------------------------------------------------------------------

/// What is on disk, asked of the environment itself.
///
/// The manifest says what was installed; this asks whether it still is. They
/// come apart more often than they should -- a half-finished install, a
/// deleted folder, a CUDA torch on a machine whose driver was removed -- and
/// the one that matters at the moment somebody presses Train is whether the
/// imports work.
bool looks_installed() {
    std::error_code ec;
    return std::filesystem::exists(python(), ec) && std::filesystem::exists(script(), ec);
}

Status status() {
    Status out;
    std::error_code ec;

    if (!std::filesystem::exists(python(), ec)) {
        out.note = "not installed";
        return out;
    }
    out.present = true;

    if (std::filesystem::exists(manifest_file(), ec)) {
        std::ifstream in(manifest_file());
        std::ostringstream buffer;
        buffer << in.rdbuf();
        const json parsed = json::parse(buffer.str(), nullptr, false);
        if (parsed.is_object()) {
            out.flavor         = flavor_from_id(parsed.value("flavor", "cpu"));
            out.python_version = parsed.value("python", "");
            out.torch_version  = parsed.value("torch", "");
            out.installed_at   = parsed.value("installed_at", "");
        }
    }

    // One interpreter start rather than one per package: importing torch is
    // most of a second on its own, and this runs when a settings page opens.
    std::string program = "import importlib, json, sys\nmissing = []\n";
    for (const std::string& name : imports(out.flavor)) {
        program += "try:\n    importlib.import_module('" + name + "')\n"
                   "except Exception:\n    missing.append('" + name + "')\n";
    }
    // And whether the cards are cards this torch can use. Asked of torch
    // rather than worked out from the version, because the answer is a list
    // the wheel carries and nothing else knows it.
    program +=
        "v = ''\nusable = []\nunusable = []\n"
        "try:\n"
        "    import torch; v = torch.__version__\n"
        "    if torch.cuda.is_available():\n"
        // Same major family, and not newer than the card. A cubin built for
        // sm_80 runs on every 8.x card above it, which is why an RTX 4070
        // (sm_89) is fine on a wheel whose list stops at sm_86 -- an exact
        // match would call two thirds of this machine broken. A Blackwell
        // card is major 12 and nothing in an 8.x/9.x list reaches it.
        "        caps = [int(a.split('_')[1]) for a in torch.cuda.get_arch_list()\n"
        "                if a.startswith('sm_')]\n"
        "        for i in range(torch.cuda.device_count()):\n"
        "            p = torch.cuda.get_device_properties(i)\n"
        "            mine = p.major * 10 + p.minor\n"
        "            fits = any(c // 10 == p.major and c <= mine for c in caps)\n"
        "            (usable if fits else unusable).append(p.name)\n"
        "except Exception:\n"
        "    try:\n        import mlx.core; v = 'mlx'\n    except Exception:\n        pass\n"
        "print(json.dumps({'missing': missing, 'torch': v, 'usable': usable,"
        " 'unusable': unusable, 'python': '%d.%d.%d' % sys.version_info[:3]}))\n";

    int               status_code = -1;
    const std::string reply       = capture({python().string(), "-c", program}, status_code);

    // The last line: a warning on import is common and lands above the answer.
    std::string last;
    for (std::istringstream lines(reply); std::getline(lines, last);) {
        if (!last.empty() && last.front() == '{') {
            break;
        }
    }
    const json parsed = json::parse(last, nullptr, false);
    if (status_code != 0 || !parsed.is_object()) {
        out.note = "the environment is there but its Python does not run";
        return out;
    }

    out.python_version = parsed.value("python", out.python_version);
    const std::string torch = parsed.value("torch", "");
    if (!torch.empty()) {
        out.torch_version = torch;
    }

    std::vector<std::string> missing;
    for (const json& name : parsed.value("missing", json::array())) {
        missing.push_back(name.get<std::string>());
    }
    for (const json& name : parsed.value("usable", json::array())) {
        out.usable_gpus.push_back(name.get<std::string>());
    }
    for (const json& name : parsed.value("unusable", json::array())) {
        out.unusable_gpus.push_back(name.get<std::string>());
    }
    out.bytes = folder_bytes(venv_dir());

    if (!missing.empty()) {
        out.note = "missing " + missing.front();
        for (std::size_t i = 1; i < missing.size(); ++i) {
            out.note += ", " + missing[i];
        }
        return out;
    }
    if (!std::filesystem::exists(script(), ec)) {
        out.note = "the trainer script is missing";
        return out;
    }
    if (out.flavor == Flavor::Cuda && out.usable_gpus.empty()
        && !out.unusable_gpus.empty()) {
        // Every card is newer than this wheel. Training would fall back to
        // the processor without saying so, which is the worst of the three
        // outcomes: hours instead of minutes, and no clue why.
        out.note = "this PyTorch has no kernels for " + out.unusable_gpus.front()
                 + " -- reinstall to pick a build that does";
        return out;
    }
    out.ready = true;
    return out;
}

bool remove(std::string& error) {
    std::error_code ec;
    std::filesystem::remove_all(root(), ec);
    if (ec) {
        error = "could not remove " + root().string() + ": " + ec.message();
        return false;
    }
    return true;
}

// ---------------------------------------------------------------------------
// The script
// ---------------------------------------------------------------------------

bool write_script(std::string& error) {
#if defined(CRUCIBLE_HAS_TRAINER_SCRIPT)
    std::error_code ec;
    std::filesystem::create_directories(root(), ec);
    if (ec) {
        error = "could not make " + root().string() + ": " + ec.message();
        return false;
    }
    std::ofstream out(script(), std::ios::binary | std::ios::trunc);
    if (!out) {
        error = "could not write " + script().string();
        return false;
    }
    out.write(reinterpret_cast<const char*>(embedded::kFinetunePy),
              static_cast<std::streamsize>(embedded::kFinetunePy_size));
    if (!out) {
        error = "could not write " + script().string();
        return false;
    }
    return true;
#else
    error = "this build has no trainer script compiled into it";
    return false;
#endif
}

// ---------------------------------------------------------------------------
// Installing
// ---------------------------------------------------------------------------

std::string Progress::label() const {
    switch (phase) {
        case Phase::Idle:          return "not installed";
        case Phase::FindingPython: return "looking for Python";
        case Phase::CreatingVenv:  return "creating the environment";
        case Phase::Installing: {
            std::string line = "installing";
            if (!step.empty()) {
                line += " " + step;
            }
            const int shown = static_cast<int>(percent * 100.0F);
            return line + "  " + std::to_string(shown) + "%";
        }
        case Phase::Verifying: return "checking it works";
        case Phase::Done:      return "ready";
        case Phase::Failed:    return error.empty() ? "failed" : error;
        case Phase::Canceled:  return "stopped";
    }
    return {};
}

Installer::~Installer() { stop(); }

Progress Installer::progress() const {
    const std::lock_guard<std::mutex> lock(mutex_);
    return progress_;
}

bool Installer::start(Flavor flavor, std::function<void()> on_change) {
    {
        const std::lock_guard<std::mutex> lock(mutex_);
        if (progress_.running()) {
            return false;
        }
    }
    if (worker_.joinable()) {
        worker_.join();
    }

    std::error_code ec;
    std::filesystem::create_directories(root(), ec);
    {
        const std::lock_guard<std::mutex> lock(mutex_);
        progress_          = Progress{};
        progress_.flavor   = flavor;
        progress_.phase    = Progress::Phase::FindingPython;
        progress_.log_file = log_file();
        log_.clear();
    }
    cancel_.store(false);
    on_change_ = std::move(on_change);
    worker_    = std::thread([this, flavor]() { run(flavor); });
    return true;
}

void Installer::cancel() {
    cancel_.store(true);
    const std::lock_guard<std::mutex> lock(child_mutex_);
    if (child_) {
        child_->terminate();
    }
}

void Installer::stop() {
    cancel();
    if (worker_.joinable()) {
        worker_.join();
    }
}

void Installer::dismiss() {
    {
        const std::lock_guard<std::mutex> lock(mutex_);
        if (progress_.running()) {
            return;
        }
    }
    if (worker_.joinable()) {
        worker_.join();
    }
    const std::lock_guard<std::mutex> lock(mutex_);
    progress_ = Progress{};
}

void Installer::set_phase(Progress::Phase phase, std::string step) {
    {
        const std::lock_guard<std::mutex> lock(mutex_);
        progress_.phase = phase;
        progress_.step  = std::move(step);
    }
    if (on_change_) {
        on_change_();
    }
}

void Installer::fail(std::string error) {
    {
        const std::lock_guard<std::mutex> lock(mutex_);
        progress_.phase = Progress::Phase::Failed;
        progress_.error = std::move(error);
        progress_.log_tail.assign(
            log_.size() > kTailLines ? log_.end() - static_cast<long>(kTailLines) : log_.begin(),
            log_.end());
    }
    if (on_change_) {
        on_change_();
    }
}

/// Run one child, moving the bar from `from` to `to` as it goes.
///
/// pip does not report a percentage of the whole job and cannot -- it does
/// not know the size of what it is about to resolve. What it does print is
/// the name and size of each wheel as it starts, which is the useful line
/// anyway: "downloading torch (797.2 MB)" answers the question somebody
/// watching a stalled bar is actually asking.
bool Installer::run_command(const std::vector<std::string>& argv, float from, float to) {
    auto        child = std::make_unique<util::Subprocess>();
    std::string error;
    if (!child->start(argv, root(), {"PIP_DISABLE_PIP_VERSION_CHECK=1",
                                     "PYTHONUNBUFFERED=1",
                                     "PIP_NO_INPUT=1"}, error)) {
        fail(argv.front() + ": " + error);
        return false;
    }
    {
        const std::lock_guard<std::mutex> lock(child_mutex_);
        child_ = std::move(child);
    }

    std::string line;
    int         seen = 0;
    for (;;) {
        util::Subprocess* running = nullptr;
        {
            const std::lock_guard<std::mutex> lock(child_mutex_);
            running = child_.get();
        }
        if (running == nullptr || !running->read_line(line)) {
            break;
        }
        {
            const std::lock_guard<std::mutex> lock(mutex_);
            log_.push_back(line);
            if (log_.size() > kMaxLogLines) {
                log_.erase(log_.begin(), log_.begin() + static_cast<long>(kMaxLogLines / 4));
            }
        }

        // "Downloading torch-2.5.1-cp312-...whl (797.2 MB)"
        const std::size_t at = line.find("Downloading ");
        if (at != std::string::npos) {
            std::string what = line.substr(at + 12);
            const std::size_t dash = what.find('-');
            std::string       name = dash == std::string::npos ? what : what.substr(0, dash);
            const std::size_t open = what.find(" (");
            if (open != std::string::npos && what.back() == ')') {
                name += " " + what.substr(open + 2, what.size() - open - 3);
            }
            ++seen;
            {
                const std::lock_guard<std::mutex> lock(mutex_);
                progress_.step = name;
                // Asymptotic: each wheel moves the bar a fraction of what is
                // left, so it always advances and never reaches the end
                // before the step it belongs to is actually over.
                progress_.percent = from + (to - from) * (1.0F - 1.0F / (1.0F + 0.12F * static_cast<float>(seen)));
            }
            if (on_change_) {
                on_change_();
            }
        }
    }

    int status = -1;
    {
        const std::lock_guard<std::mutex> lock(child_mutex_);
        if (child_) {
            status = child_->wait();
            child_.reset();
        }
    }

    {
        const std::lock_guard<std::mutex> lock(mutex_);
        std::ofstream out(progress_.log_file, std::ios::app);
        for (const std::string& entry : log_) {
            out << entry << '\n';
        }
        log_.clear();
        progress_.percent = to;
    }

    if (cancel_.load()) {
        const std::lock_guard<std::mutex> lock(mutex_);
        progress_.phase = Progress::Phase::Canceled;
        return false;
    }
    if (status != 0) {
        fail(argv.front() + " exited " + std::to_string(status));
        return false;
    }
    return true;
}

void Installer::run(Flavor flavor) {
    // --- a Python to build from --------------------------------------------
    set_phase(Progress::Phase::FindingPython);
    std::string                 found;
    const std::filesystem::path host = host_python(found);
    if (host.empty()) {
        fail(found.empty()
                 ? "no Python on this machine. " + python_hint()
                 : "Python " + found + " is too old -- 3.10 or newer is needed. "
                       + python_hint());
        return;
    }

    std::string error;
    if (!write_script(error)) {
        fail(error);
        return;
    }

    // --- the environment ----------------------------------------------------
    //
    // Removed first rather than reused. A venv that failed halfway through an
    // install is a folder full of half-resolved packages, and pip is
    // perfectly happy to leave it that way; starting again is a few minutes
    // and starting from that is a support thread.
    set_phase(Progress::Phase::CreatingVenv, host.string());
    std::error_code ec;
    std::filesystem::remove_all(venv_dir(), ec);
    std::filesystem::remove(log_file(), ec);

    if (!run_command({host.string(), "-m", "venv", venv_dir().string()}, 0.0F, 0.04F)) {
        return;
    }
    if (!run_command({python().string(), "-m", "pip", "install", "--upgrade",
                      "pip", "wheel", "setuptools"},
                     0.04F, 0.08F)) {
        return;
    }

    // --- the packages -------------------------------------------------------
    set_phase(Progress::Phase::Installing);
    const std::vector<Step> steps = plan(flavor);

    // Weighted by download size rather than by count: torch is most of the
    // wait and one of seven steps, and a bar that gives it a seventh of the
    // width sits at 14% for four minutes.
    const float torch_share = flavor == Flavor::Cuda ? 0.78F : 0.55F;
    float       at          = 0.08F;
    for (std::size_t i = 0; i < steps.size(); ++i) {
        const Step& step  = steps[i];
        const float share = i == 0 ? torch_share
                                   : (0.92F - torch_share - 0.08F)
                                         / static_cast<float>(steps.size() - 1);
        const float to    = std::min(at + share, 0.97F);

        {
            const std::lock_guard<std::mutex> lock(mutex_);
            progress_.step = step.label;
        }
        if (on_change_) {
            on_change_();
        }

        // --no-cache-dir, because the cache is not inside the folder this
        // promises to be removable by deleting. Measured: a CUDA install
        // leaves 2.7 GB in ~/.cache/pip that neither Remove nor
        // `crucible --uninstall` would ever reclaim, on top of the 7 GB it
        // admits to. The cost is a re-download on reinstall, which is rare,
        // and the alternative is lying about the footprint.
        std::vector<std::string> argv{python().string(), "-m", "pip", "install",
                                      "--no-cache-dir"};
        if (!step.index_url.empty()) {
            argv.emplace_back("--index-url");
            argv.push_back(step.index_url);
        }
        argv.insert(argv.end(), step.packages.begin(), step.packages.end());
        if (!run_command(argv, at, to)) {
            return;
        }
        at = to;
    }

    // --- does it actually work ---------------------------------------------
    //
    // Importing is the test, not "pip said OK". A CUDA torch on a machine
    // whose driver is older than the wheel installs perfectly and raises on
    // the first import, and finding that out here costs a second, while
    // finding it out at the start of a run costs the run.
    set_phase(Progress::Phase::Verifying);
    const std::vector<std::string> names = imports(flavor);
    std::string                    line  = "import " + names.front();
    for (std::size_t i = 1; i < names.size(); ++i) {
        line += ", " + names[i];
    }
    if (!run_command({python().string(), "-c", line}, 0.97F, 1.0F)) {
        return;
    }

    const Status now = status();
    json         manifest;
    manifest["flavor"]       = std::string(flavor_id(flavor));
    manifest["python"]       = now.python_version;
    manifest["torch"]        = now.torch_version;
    manifest["installed_at"] = now_stamp();
    manifest["host_python"]  = host.string();
    {
        std::ofstream out(manifest_file(), std::ios::trunc);
        out << manifest.dump(2) << '\n';
    }

    {
        const std::lock_guard<std::mutex> lock(mutex_);
        progress_.phase   = Progress::Phase::Done;
        progress_.percent = 1.0F;
        progress_.step.clear();
    }
    if (on_change_) {
        on_change_();
    }
}

}  // namespace crucible::lab::pyenv
