# Turn a binary file into a C++ array.
#
# Used for the interface font. A font is the one asset Crucible cannot draw for
# itself, and looking for it on disk at runtime would mean an install layout and
# a search path for a typeface -- which is exactly the machinery the flame mark
# avoids by being vector shapes. Compiling it in costs a megabyte of generated
# source and about a fifth of a second, measured, and removes the whole class of
# "it looked right on my machine".
#
# Run with -P: cmake -DIN=... -DOUT=... -DSYMBOL=... -P EmbedBinary.cmake
if(NOT DEFINED IN OR NOT DEFINED OUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "EmbedBinary.cmake needs IN, OUT and SYMBOL")
endif()

# The font was the only caller for a long time and the namespace was written
# into the template. The window's mark is embedded the same way now, and it is
# not a font.
if(NOT DEFINED NAMESPACE)
    set(NAMESPACE "crucible::gui::fonts")
endif()

file(READ "${IN}" _hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
string(LENGTH "${_hex}" _hex_length)
math(EXPR _size "${_hex_length} / 2")

file(WRITE "${OUT}"
"// Generated by cmake/EmbedBinary.cmake from ${IN}. Do not edit.\n"
"namespace ${NAMESPACE} {\n"
"extern const unsigned char ${SYMBOL}[];\n"
"extern const unsigned int  ${SYMBOL}_size;\n"
"const unsigned char ${SYMBOL}[] = {${_bytes}};\n"
"const unsigned int  ${SYMBOL}_size = ${_size}u;\n"
"}  // namespace ${NAMESPACE}\n")
